#! /bin/sh

feh --bg-fill ~/Pictures/IMG_20210828_104753.jpg

# Keyboard layout
setxkbmap fi nodeadkeys

# Composite manager
pgrep picom ||
picom \
	--backend xrender \
	--inactive-opacity=1.0 \
	--shadow-radius=0 \
	--shadow-opacity=0 \
	--fade-delta 6 \
	--fade-in-step=0.03 \
	--fade-out-step=0.03 \
	--frame-opacity=1.0 &

# Scroll
pgrep imwheel || imwheel -b 45

# Notifications
deadd-notification-center &

export _JAVA_AWT_WM_NONREPARENTING=1

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
